version: "3.9"
services:
  web:
    # image: neural_frontend
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app

  nn:
    # image: nn_api
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
      - ../Experiments:/app/static