version: "3.8"
services:
  web:
    # image: neural_frontend
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
    networks:
      - home

  nn:
    # image: nn_api
    build: ./api
    # command: python -c "import torch; print(torch.cuda.is_available())"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    ports:
      - 5000:5000
    volumes:
      - ./api:/app
      - ./api/static:/app/static
    networks:
      - home

networks:
  home:
    name: my-bridge